import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F2F1F6",
  },
  personIcon: {
    color: "black",
    flexDirection: "row",
    alignSelf: "flex-end",
    padding: 20,
  },
  title: {
    fontSize: 24,
    marginBottom: 10,
    marginLeft: 15,
    fontFamily: "Assistant_700Bold",
  },
  scoreMenu: {
    borderRadius: 20,
    backgroundColor: "#BB4976",
    flexDirection: "row",
    justifyContent: "space-between",
    height: 35,
    width: "90%",
    alignItems: "center",
    alignSelf: "center",
    marginBottom: 50,
    paddingHorizontal: 5,
    paddingRight: 40,
  },
  scoreMenuText: {
    color: "white",
    textAlign: "center",
    fontSize: 18,
    fontFamily: "Assistant_400Regular",
  },
  activeText: {
    backgroundColor: "white",
    color: "#BB4976",
    borderRadius: 15,
    padding: 3,
    paddingHorizontal: 20,
    fontSize: 18,
  },
  top3: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 50,
    marginHorizontal: 50,
  },
  trophyText: {
    flexDirection: "column",
    marginTop: -25,
  },
  top3Text: {
    fontSize: 18,
    color: "black",
    textAlign: "center",
    fontFamily: "Assistant_700Bold",
  },
  firstText: {
    fontSize: 24,
  },
  trophies: {
    width: 90,
    height: 90,
    borderRadius: 90 / 2,
    backgroundColor: "white",
    padding: 10,
    paddingTop: 20,
    textAlign: "center",
    alignItems: "center",
  },
  firstPlace: {
    width: 100,
    height: 100,
    borderRadius: 100 / 2,
    backgroundColor: "white",
    padding: 10,
    textAlign: "center",
    alignItems: "center",
    marginTop: -25,
    paddingTop: 15,
  },
  flatListContainer: {
    flex: 1,
    marginTop: 50,
  },
  scoreList: {
    flexDirection: "row",
    alignSelf: "stretch",
    backgroundColor: "white",
    height: 72,
    marginBottom: 54,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  rank: {
    borderColor: "#d3d3d3",
    borderWidth: 4,
    borderRadius: 8,
    padding: 5,
    marginVertical: 10,
    marginLeft: 20,
    height: 48,
    width: 48,
    textAlign: "center",
    fontSize: 16,
    paddingTop: 10,
    fontFamily: "Inter-SemiBold",
  },
  rankText: {
    color: "#a9a9a9",
    fontSize: 16,
    fontFamily: "Assistant_400Regular",
    fontSize: 24,
    alignSelf: "center",
  },
  rankName: {
    marginRight: "45%",
  },
  score: {
    marginRight: 50,
  },
});

export default styles;
